{
 "title": "大盘",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "HKHostIp",
    "query": {
     "query": "label_values(machine_memory_bytes, instance)"
    }
   },
   {
    "name": "SHHostIp",
    "query": {
     "query": "label_values(machine_memory_bytes, instance)"
    }
   },
   {
    "name": "HKInstance",
    "label": "香港实例",
    "query": {
     "query": "label_values(probe_success{}, instance)"
    }
   },
   {
    "name": "SHInstance",
    "label": "上海实例",
    "query": {
     "query": "label_values(probe_success{}, instance)"
    }
   },
   {
    "name": "HKRDSInstanceId",
    "query": {
     "query": "label_values(arms_cms_rds_cpu_usage_average{region=~\"$HKRegion\"},id)"
    }
   },
   {
    "name": "HKRegion",
    "query": {
     "query": "label_values(arms_cms_aliyun_region, region)"
    }
   },
   {
    "name": "SHRDSInstanceId",
    "query": {
     "query": "label_values(arms_cms_rds_cpu_usage_average{region=~\"$SHRegion\"},id)"
    }
   },
   {
    "name": "SHRegion",
    "query": {
     "query": "label_values(arms_cms_aliyun_region, region)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "香港节点",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "node_uname_info - 0" },
    { "expr": "node_memory_MemTotal_bytes - 0" },
    {
     "expr": "count(node_cpu_seconds_total{mode='system'}) by (instance)"
    },
    {
     "expr": "sum(time() - node_boot_time_seconds)by(instance)"
    },
    {
     "expr": "max((node_filesystem_size_bytes{fstype=~\"ext.?|xfs\"}-node_filesystem_free_bytes{fstype=~\"ext.?|xfs\"}) *100/(node_filesystem_avail_bytes {fstype=~\"ext.?|xfs\"}+(node_filesystem_size_bytes{fstype=~\"ext.?|xfs\"}-node_filesystem_free_bytes{fstype=~\"ext.?|xfs\"})))by(instance)"
    },
    {
     "expr": "(1 - avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) by (instance)) * 100"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{} / (node_memory_MemTotal_bytes{})))* 100"
    },
    {
     "expr": "max(irate(node_disk_read_bytes_total{}[5m])) by (instance)",
     "legendFormat": "最大读取"
    },
    {
     "expr": "max(irate(node_disk_written_bytes_total{}[5m])) by (instance)",
     "legendFormat": "最大写入"
    },
    {
     "expr": "max(irate(node_network_receive_bytes_total{}[5m])*8) by (instance)",
     "legendFormat": "下载带宽"
    },
    {
     "expr": "max(irate(node_network_transmit_bytes_total{}[5m])*8) by (instance)",
     "legendFormat": "上传带宽"
    }
   ]
  },
  {
   "title": "上海节点",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "targets": [
    { "expr": "node_uname_info - 0" },
    { "expr": "node_memory_MemTotal_bytes - 0" },
    {
     "expr": "count(node_cpu_seconds_total{mode='system'}) by (instance)"
    },
    {
     "expr": "sum(time() - node_boot_time_seconds)by(instance)"
    },
    {
     "expr": "max((node_filesystem_size_bytes{fstype=~\"ext.?|xfs\"}-node_filesystem_free_bytes{fstype=~\"ext.?|xfs\"}) *100/(node_filesystem_avail_bytes {fstype=~\"ext.?|xfs\"}+(node_filesystem_size_bytes{fstype=~\"ext.?|xfs\"}-node_filesystem_free_bytes{fstype=~\"ext.?|xfs\"})))by(instance)"
    },
    {
     "expr": "(1 - avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) by (instance)) * 100"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{} / (node_memory_MemTotal_bytes{})))* 100"
    },
    {
     "expr": "max(irate(node_disk_read_bytes_total{}[5m])) by (instance)",
     "legendFormat": "最大读取"
    },
    {
     "expr": "max(irate(node_disk_written_bytes_total{}[5m])) by (instance)",
     "legendFormat": "最大写入"
    },
    {
     "expr": "max(irate(node_network_receive_bytes_total{}[5m])*8) by (instance)",
     "legendFormat": "下载带宽"
    },
    {
     "expr": "max(irate(node_network_transmit_bytes_total{}[5m])*8) by (instance)",
     "legendFormat": "上传带宽"
    }
   ]
  },
  {
   "title": "香港Cluster CPU usage (1m avg)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 16 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",instance=~\"^$HKHostIp.*\"}[1m])) / sum (machine_cpu_cores{instance=~\"^$HKHostIp.*\"}) * 100"
    }
   ]
  },
  {
   "title": "香港Cluster memory usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 16 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\",instance=~\"^$HKHostIp.*$\"}) / sum (machine_memory_bytes{instance=~\"^$HKHostIp.*$\"}) * 100"
    }
   ]
  },
  {
   "title": "香港Cluster filesystem usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 16 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/.*$\",id=\"/\",instance=~\"^$HKHostIp.*\"}) / sum (container_fs_limit_bytes{device=~\"^/dev/.*$\",id=\"/\",instance=~\"^$HKHostIp.*\"}) * 100"
    }
   ]
  },
  {
   "title": "上海Cluster memory usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 16 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\",instance=~\"^$SHHostIp.*$\"}) / sum (machine_memory_bytes{instance=~\"^$SHHostIp.*$\"}) * 100"
    }
   ]
  },
  {
   "title": "上海Cluster filesystem usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 16 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/.*$\",id=\"/\",instance=~\"^$SHHostIp.*\"}) / sum (container_fs_limit_bytes{device=~\"^/dev/.*$\",id=\"/\",instance=~\"^$SHHostIp.*\"}) * 100"
    }
   ]
  },
  {
   "title": "上海Cluster CPU usage (1m avg)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 16 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",instance=~\"^$SHHostIp.*\"}[1m])) / sum (machine_cpu_cores{instance=~\"^$SHHostIp.*\"}) * 100"
    }
   ]
  },
  {
   "title": "香港RDS CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "arms_cms_rds_cpu_usage_average{id=~\"$HKRDSInstanceId\",region=~\"$HKRegion\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "香港RDS Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "arms_cms_rds_memory_usage{id=~\"$HKRDSInstanceId\",region=~\"$HKRegion\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "香港RDS Disk Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 20 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "arms_cms_rds_disk_usage{id=~\"$HKRDSInstanceId\",region=~\"$HKRegion\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "上海RDS CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "arms_cms_rds_cpu_usage_average{id=~\"$SHRDSInstanceId\",region=~\"$SHRegion\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "上海RDS Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 27 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "arms_cms_rds_memory_usage{id=~\"$SHRDSInstanceId\",region=~\"$SHRegion\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "上海RDS Disk Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 27 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "arms_cms_rds_disk_usage{id=~\"$SHRDSInstanceId\",region=~\"$SHRegion\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "香港服务状态",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "probe_success{instance=~\"$HKInstance\"} - 0"
    },
    {
     "expr": "probe_http_ssl{instance=~\"$HKInstance\"} - 0"
    },
    {
     "expr": "probe_http_status_code{instance=~\"$HKInstance\"} - 0"
    },
    {
     "expr": "probe_ssl_earliest_cert_expiry{instance=~\"$HKInstance\"} - time()"
    }
   ]
  },
  {
   "title": "上海服务状态",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "probe_success{instance=~\"$SHInstance\"} - 0"
    },
    {
     "expr": "probe_http_ssl{instance=~\"$SHInstance\"} - 0"
    },
    {
     "expr": "probe_http_status_code{instance=~\"$SHInstance\"} - 0"
    },
    {
     "expr": "probe_ssl_earliest_cert_expiry{instance=~\"$SHInstance\"} - time()"
    }
   ]
  }
 ]
}